# Adapted from https://github.com/withastro/starlight/blob/main/.github/workflows/format.yml

name: Format

on:
  push:
    branches:
      - next

jobs:
  format:
    # Prevents running workflow on forks
    if: ${{ github.repository_owner == 'tauri-apps' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # Needs access to push to main
          token: ${{ secrets.ORG_TAURI_BOT_PAT }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm i
      - name: Format with Prettier
        run: pnpm format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] format'
          branch: ${{ github.head_ref }}
          commit_user_name: tauri-bot
          commit_user_email: tauri-bot@users.noreply.github.com
